--liquibase formatted sql

--changeset dhruv:1
CREATE TABLE AIRLINES
   (
		AIRLINE CHAR(2) NOT NULL CONSTRAINT AIRLINES_PK PRIMARY KEY,
		AIRLINE_FULL VARCHAR(24),
		BASIC_RATE DOUBLE PRECISION,
		DISTANCE_DISCOUNT DOUBLE PRECISION,
		BUSINESS_LEVEL_FACTOR DOUBLE PRECISION,
		FIRSTCLASS_LEVEL_FACTOR DOUBLE PRECISION,
		ECONOMY_SEATS INTEGER,
		BUSINESS_SEATS INTEGER,
		FIRSTCLASS_SEATS INTEGER
   );
