--liquibase formatted sql

--changeset dhruv:1
CREATE TABLE COUNTRIES
   (
		COUNTRY VARCHAR(26) NOT NULL CONSTRAINT COUNTRIES_UNQ_NM Unique,
		COUNTRY_ISO_CODE CHAR(2) NOT NULL CONSTRAINT COUNTRIES_PK PRIMARY KEY,
		REGION VARCHAR(26)
   );

